name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: |
        cd build/
        git init
        git add .
        git commit -m 'Deploy to github pages'
        git push --force https://${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
